version: '3.8'

services:
  arangodb:
    image: arangodb/arangodb:3.7.3
    container_name: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
      GLIBCXX_FORCE_NEW: '1'
    ports:
      - "8529:8529"
    restart: unless-stopped
    networks:
      - arango-network
    mac_address: 02:42:ac:11:00:02
    hostname: 44b94bf10934

networks:
  arango-network:
    driver: bridge
